### PR TITLE
IF: Include `block_state::valid` in the snapshot.

### PR DESCRIPTION
**Pull request by greg7mdp**

### CODE REVIEW

**Comment by greg7mdp** [comment]
@linh2931 this is a PR adding the snapshot fix into your branch.

**Review by heifner — APPROVED** [review]

**Review by linh2931 — APPROVED** [review]
Thanks. No changes to the tests?

**Comment by greg7mdp** [comment]
> Thanks. No changes to the tests?

No change. I guess we don't have a test that uses the new `valid` member yet.

**Comment by heifner** [comment]
> > Thanks. No changes to the tests?
> 
> No change. I guess we don't have a test that uses the new `valid` member yet.

Don't you need to udpate:  `unittests/snapshots/snap_v7.bin.*`

**Comment by heifner** [comment]
> > Don't you need to udpate: `unittests/snapshots/snap_v7.bin.*`
> 
> I didn't have to. The test that uses those files (`test_compatible_versions` in `unittests`) doesn't run in IF mode I guess, so it must save the `block_state_legacy` in the variant.

That is a test we certainly want to run in both modes.

**Comment by greg7mdp** [comment]
> That is a test we certainly want to run in both modes.

Hum, not sure about this particular one, it is meant to verify that we can load old snapshot versions.

**Pull request merged**
