### PR TITLE
[3.1] Pinned Build Script Backport Omnibus

### PR DESCRIPTION
**Pull request by kj4ezj**
I done f***ed up working on [issue 735](https://github.com/AntelopeIO/leap/issues/735). I have already done tasks in Leap since I joined the ENF so I should already know that we PR to the oldest base branch we wish changes be included in, then forward-merge through release branches until we get to `main`. This is a more appropriate `git`-native strategy than what we did at B1, cherry-picking commits to each release branch and back-porting. I suppose I have four years of habit to undo. I am sorry!

This pull request cherry-picks commits in order from the following pull requests that have already been merged to `main`:
1. [Pull Request 812](https://github.com/AntelopeIO/leap/pull/812) - Pinned Build Script Linter Changes
1. [Pull Request 835](https://github.com/AntelopeIO/leap/pull/835) - Change ASCII Art Banner in Build Script
1. [Pull Request 847](https://github.com/AntelopeIO/leap/pull/847) - Restore `libcurl4-openssl-dev`
1. [Pull Request 849](https://github.com/AntelopeIO/leap/pull/849) - Fix `README.md` Formatting

Back-porting these changes will enable me to follow the correct process to address this issue moving forward. A few commits were no-ops, but no new changes have been made.

Based on feedback, I'll add that I think applying these changes to all supported feature branches is important because they are already in `main`, so future changes to the pinned build script will apply and forward-merge cleanly. This is in addition to the value added by the individual changes themselves, such as linter fixes.

## See Also
1. [Pull Request 833](https://github.com/AntelopeIO/leap/pull/833) - Fix Pinned Build on Ubuntu 22.04
    - Reverts [pull request 799](https://github.com/AntelopeIO/leap/pull/799)
1. [Pull Request 812](https://github.com/AntelopeIO/leap/pull/812) - Pinned Build Script Linter Changes
1. [Pull Request 835](https://github.com/AntelopeIO/leap/pull/835) - Change ASCII Art Banner in Build Script
1. ~~[Pull Request 832](https://github.com/AntelopeIO/leap/pull/832) - Roll `install_deps.sh` into `pinned_build.sh`~~
1. [Pull Request 847](https://github.com/AntelopeIO/leap/pull/847) - Restore `libcurl4-openssl-dev`
1. [Pull Request 849](https://github.com/AntelopeIO/leap/pull/849) - Fix `README.md` Formatting
1. [Pull Request 870](https://github.com/AntelopeIO/leap/pull/870) - Pinned Build Script Backport Omnibus
1. [Pull Request 857](https://github.com/AntelopeIO/leap/pull/857) - Simplify Pinned Build Scripts
1. [Pull Request 811](https://github.com/AntelopeIO/leap/pull/811) - Pinned Build Script Changes

### CODE REVIEW

**Review by ScottBailey — APPROVED** [review]
It's déjà vu all over again.

**Review by spoonincode — CHANGES_REQUESTED** [review]
I am not sure these changes really ought to qualify for backporting. I'm very reluctant to make non-critical changes to scripts that have no test coverage and a history of being persnickety.

In particular the ASCII art change is very superficial, and `libcurl4-openssl-dev` is already present making all of `install_deps.sh`'s changes unnecessary.

The linter changes are mostly just "clean ups" which aren't something that is typically backported. There _might_ be a stretch argument that it solves a 'real' defect if someone has a space in their path; but it's not clear the build otherwise works correctly in such an environment anyways.

That leaves the README changes, which really is just reiterating to users they don't need to use sudo.

**Comment by kj4ezj** [comment]
As I mentioned in DMs and the pull request description, the code changes here have already been approved and merged by engineers including yourself, and it will be easier for everyone if all of the supported base branches remain in lock-step so that changes made to this code in the future apply and forward-merge cleanly.

> I am not sure these changes really ought to qualify for backporting. I'm very reluctant to make non-critical changes to scripts that have no test coverage and a history of being persnickety.

The CI system has never been held to the requirements to backport application code before. Even if it were, this is not a "backport" - these changes should have been made to this branch originally and this is resolving that mistake.

The AI-generated ASCII art banner is just for fun, sure...and I hope we can have fun with our community! However, _all_ of our BASH code should be passing industry-standard linters. These tools help reduce the incidence of bugs, increase compatibility across platforms, and ensure the meaning of code is unambiguous.

> I'm very reluctant to make non-critical changes to scripts that have no test coverage and a history of being persnickety.

This is exactly why we should be linting.

> There might be a stretch argument that it solves a 'real' defect if someone has a space in their path; but it's not clear the build otherwise works correctly in such an environment anyways.

Path issues are an incredibly valuable bug the linter has caught. I don't think it is acceptable for our code quality standard to be "well this one component has a bug so it is okay if every other component has the same bug because our code doesn't work anyways, we might as well not fix it." That seems absurd to me. I don't expect build path issues to be fixed on this branch, but they should eventually be fixed and I should not need to prove the absence of a bug in the application code to fix a bug in the CI code. When application engineers fix the build, there is no reason I should have to circle back to this script because it doesn't work when I can just fix it right now.

Overall, I am extremely disappointed in the amount of friction I have gotten trying to improve these scripts. I am capable of excellence and I have been working on build systems for years and years, but my hands keep getting tied behind my back.

The obvious question here is, if not `release/3.1`, then which branch is acceptable to start from? I believe it is in the best interest of both ourselves and our customers for us to have a working pinned build on all supported branches. The product team was just asked by the customer to support two previous versions and I do not know whether that will be the case or not, but I am trying to get ahead of it. If we can't agree that pinned build changes should be done on any release branches, then the pinned build can't be automated on release branches.

**Comment by spoonincode** [comment]
The changes were approved in the context of going in to main.

The criteria for changes that are allowed to a stable branch isn't something we have a definitive rule set on (and we've made some.. interesting.. exceptions over the years). But in general, clean up and style fixes are not in scope for stable branches. Changes to stable branches really need to be solving a concrete defect. Even then, the risk/benefit tradeoff needs to be considered for stable branch changes.

So, something like refactoring `install_deps.sh` or changing ASCII art seems pretty clear cut not appropriate. The linter changes _maybe_ passes muster: they do solve a concrete defect in that the script would have misbehaved when used in a path with spaces. But the risk/reward on that one feels off due to the scripts having literally no tests and historically being a persnickety affair: fix one thing break another. And there are a lot of changes in there well beyond just trying to fix a defect. Plus, no one has ever reported that defect and it's not clear it's dire enough to make a risky change; I'm just reaching for any reason it could be considered acceptable on stable.

> The CI system has never been held to the requirements to backport application code before

afaict there is nothing in this PR related to CI, nor are any of the changes required for proper CI operation.

**Comment by kj4ezj** [comment]
Closing based on discussion on video :)

**Pull request closed without merging**
