### PR TITLE
[5.0] Update to latest version of BLS12 submodule with clearer conversion parameters

### PR DESCRIPTION
**Pull request by greg7mdp**

### CODE REVIEW

**Review by linh2931 — APPROVED** [review]
You'll still need to do a merge from 5.0 to `main` even though it will be an `empty` merge for tracking.

**Comment by greg7mdp** [comment]
> You'll still need to do a merge from 5.0 to `main` even though it will be an `empty` merge for tracking.

These changes aren't in `main` yet, so I should be able to do the normal merge.

**Review by heifner — APPROVED** [review]

**Comment by ericpassmore** [comment]
Note:start
group: CLEANCODE
category: INTERNALS
summary: Update to latest version of BLS12 submodule with clearer conversion parameters.
Note:end

**Comment by ericpassmore** [comment]
Note:start
category: Chores
component: Internals
summary: Update to latest version of BLS12 submodule with clearer conversion parameters.
Note:end

**Pull request merged**
