### PR TITLE
[5.0] fix some minor misspellings

### LINKED ISSUE #2396: Typo (glock -> block) in description of get_block_header_state in the chain API plugin yaml
https://github.com/AntelopeIO/leap/blob/99ee7a7affc62b759c3ad50ad918f32dba274a46/plugins/chain_api_plugin/chain.swagger.yaml#L191

### PR DESCRIPTION
**Pull request by spoonincode**
Resolves  #2396

### CODE REVIEW

**Review by heifner — APPROVED** [review]
I don't see the point of backporting this.

**Comment by spoonincode** [comment]
The glock/block mixup actually makes its way to the public doc website which certainly warrants that one being fixed imo
https://docs.eosnetwork.com/apis/leap/latest/chain.api/#operation/get_block_header_state

**Review by linh2931 — APPROVED** [review]

**Review by greg7mdp — APPROVED** [review]

**Comment by spoonincode** [comment]
> I don't see the point of backporting this.

oh yeah that description was entirely changed in spring anyways. oh well

**Comment by ericpassmore** [comment]
Note:start
category: Chores
component: Internal
summary: Fix minor misspellings.
Note:end

**Pull request merged**
