### PR TITLE
New protocol features activation was added to the bootstrap process

### PR DESCRIPTION
**Pull request by jolly-fellow**
New protocol features: GET_CODE_HASH, CRYPTO_PRIMITIVES, GET_BLOCK_NUM were added.

### CODE REVIEW

**Review by heifner — CHANGES_REQUESTED** [review]
I think we need to backport this to release/3.1 & release/3.2

**Comment by jolly-fellow** [comment]
> I think we need to backport this to release/3.1 & release/3.2

Done in https://github.com/AntelopeIO/leap/pull/747 and #746 Approve them please.

**Comment by heifner** [comment]
> > I think we need to backport this to release/3.1 & release/3.2
> 
> Done in #747 and #746 Approve them please.

The process for bug fixes to old release branches is as follows:
- Create a PR to release/3.1 which you have in #747 (although please put the info from this PR description in that PR description)
- Once approved, merge into release/3.1
- Create a branch that merges release/3.1 into release/3.2
- Create a PR into release/3.2 from that branch
- Once approved, merge into release/3.2
- Create a branch that merges release/3.2 into main
- Create a PR into main from that branch
- Once approved, merge into main

**Comment by jolly-fellow** [comment]
> > > I think we need to backport this to release/3.1 & release/3.2
> > 
> > 
> > Done in #747 and #746 Approve them please.
> 
> The process for bug fixes to old release branches is as follows:
> 
>     * Create a PR to release/3.1 which you have in [Backport to 3.1 of bootstrap new protocol features activation #747](https://github.com/AntelopeIO/leap/pull/747) (although please put the info from this PR description in that PR description)
> 
>     * Once approved, merge into release/3.1
> 
>     * Create a branch that merges release/3.1 into release/3.2
> 
>     * Create a PR into release/3.2 from that branch
> 
>     * Once approved, merge into release/3.2
> 
>     * Create a branch that merges release/3.2 into main
> 
>     * Create a PR into main from that branch
> 
>     * Once approved, merge into main

Thanks for the explanation.

**Pull request closed without merging**
