### PR TITLE
Docs:  http protocol spec for producer plugin

### LINKED ISSUE #87: "params" object is not required for set_whitelist_blacklist, add_greylist_accounts, remove_greylist_accounts
https://github.com/AntelopeIO/leap/blob/main/plugins/producer_api_plugin/producer.swagger.yaml#L330

This is correct:

```
curl -d '{"actor_whitelist":[],"actor_blacklist":[],"contract_whitelist":[],"contract_blacklist":[],"action_blacklist":[],"key_blacklist":[]}' http://127.0.0.1:8888/v1/producer/set_whitelist_blacklist
```

There is no "params".

### PR DESCRIPTION
**Pull request by ericpassmore**
## Description 
Complete update of plugin_producer HTTP protocol documentation. One file changed. 

## Fixes
resolved #87 

## Summary 
- corrected return codes, filling in 400 errors when missing 
- corrected schemas both provided and returned 
- updated descriptions
- added get_account_ram_corrections which was missing from docs

### CODE REVIEW

**Comment by ericpassmore** [comment]
Exceeded CPU limit and that failed transferring sys tokens to account2. Should we re-run the tests, or is more debugging required?

`2022-09-15T20:56:19.829943  cmd: ['programs/cleos/cleos', '--url', 'http://localhost:8890', '--wallet-url', 'http://localhost:9899', '--no-auto-keosd', 'push', 'transaction', '-j', '{"actions":[{"account":"eosio.token","name":"transfer","authorization":[{"actor":"account2","permission":"active"}],"data":{"from":"account2","to":"account1","quantity":"10.0001 SYS","memo":"tx-4"},"compression":"none"}]}']
2022-09-15T20:56:19.849818     ERROR: b'\x1b[31mError 3080004: Transaction exceeded the current CPU usage limit imposed on the transaction\x1b[0m\n\x1b[33mError Details:\ntransaction d1c73b53e575595b1e5577638b085069205d99b64f3454f7f43e54a6483b72e0 exceeded failure limit for account account2\x1b[0m\n'
2022-09-15T20:56:19.849958  ERROR: Exception during push transaction.  cmd Duration=0.020 sec.  Error 3080004: Transaction exceeded the current CPU usage limit imposed on the transaction
Error Details:
transaction d1c73b53e575595b1e5577638b085069205d99b64f3454f7f43e54a6483b72e0 exceeded failure limit for account account2`

**Comment by heifner** [comment]
> Exceeded CPU limit and that failed transferring sys tokens to account2. Should we re-run the tests, or is more debugging required?

This is a real issue. Would you mind creating a github issue for it. Should be an easy fix.

**Comment by ericpassmore** [comment]
```
git diff --name-only 2aefa0d3c 44ec05bfc
plugins/producer_api_plugin/producer.swagger.yaml
```

**Comment by ericpassmore** [comment]
tracking failure in issue #174

**Review by lparisc — APPROVED** [review]
Looks great. Just a small typo in the description field of most endpoints: Retreives --> Retrieves

**Pull request merged**
