### PR TITLE
Fix clang++16 warnings

### PR DESCRIPTION
**Pull request by heifner**
Just add `std::` to `move` and `forward`.

### CODE REVIEW

**Comment by linh2931** [comment]
Those two warnings were annoying. Thanks for fixing them.

**Comment by heifner** [comment]
Superseded by #1027

**Comment by greg7mdp** [comment]
Sorry, I missed the fact that you were doing this too!

**Comment by heifner** [comment]
> Sorry, I missed the fact that you were doing this too!

No problem.

**Pull request closed without merging**
